deployment:
  tasks:
    - export DEPLOYPATH=/home/akibwork/public_html/mcu
    - /bin/cp -R * $DEPLOYPATHdeployment:
  tasks:
    - export DEPLOYPATH=/home/akibwork/public_html/mcu
    - /bin/cp -R * $DEPLOYPATH